/**
 * Project configuration
 * This file is auto-generated by pipecat-cli
 * Converted to TypeScript with proper type safety
 */

export const AVAILABLE_TRANSPORTS: string[] = ["daily", "smallwebrtc"];

export type TransportType = "daily" | "smallwebrtc";

export const DEFAULT_TRANSPORT: string = "smallwebrtc";

interface TransportConfig {
  endpoint: string;
  requestData: Record<string, unknown>;
  headers?: Headers;
}

interface TransportConfigMap {
  [key: string]: TransportConfig;
  daily: TransportConfig;
  smallwebrtc: TransportConfig;
}

const botStartUrl =
  import.meta.env.VITE_BOT_START_URL || "http://localhost:7860/start";
const botStartPublicApiKey = import.meta.env.VITE_BOT_START_PUBLIC_API_KEY;

if (!import.meta.env.VITE_BOT_START_URL) {
  console.warn(
    "VITE_BOT_START_URL not configured, using default: http://localhost:7860/start"
  );
}

const dailyConfig: TransportConfig = {
  endpoint: botStartUrl,
  requestData: {
    createDailyRoom: true,
    dailyRoomProperties: { start_video_off: true },
    transport: "daily",
  },
};

if (botStartPublicApiKey) {
  dailyConfig.headers = new Headers({
    Authorization: `Bearer ${botStartPublicApiKey}`,
  });
}

const smallWebRTCConfig: TransportConfig = {
  endpoint: botStartUrl,
  requestData: {
    createDailyRoom: false,
    enableDefaultIceServers: true,
    transport: "webrtc",
  },
};

if (botStartPublicApiKey) {
  smallWebRTCConfig.headers = new Headers({
    Authorization: `Bearer ${botStartPublicApiKey}`,
  });
}

export const TRANSPORT_CONFIG: TransportConfigMap = {
  daily: dailyConfig,
  smallwebrtc: smallWebRTCConfig,
};

/**
 * Create a transport instance based on the transport type
 * Uses dynamic imports to only load the required transport library
 * @param transportType - The type of transport to create ('daily' or 'smallwebrtc')
 * @returns Promise resolving to a transport instance
 * @throws Error if transport type is unsupported
 */
export async function createTransport(
  transportType: TransportType
): Promise<any> {
  switch (transportType) {
    case "daily": {
      const { DailyTransport: DailyTransportClass } = await import(
        "@pipecat-ai/daily-transport"
      );
      return new DailyTransportClass();
    }

    case "smallwebrtc": {
      const { SmallWebRTCTransport: SmallWebRTCTransportClass } = await import(
        "@pipecat-ai/small-webrtc-transport"
      );
      return new SmallWebRTCTransportClass();
    }

    default:
      throw new Error(`Unsupported transport type: ${transportType}`);
  }
}
